packages:
  - "packages/*"
  - "apps/*"

catalog:
  "@types/node": ^24
  "@types/react": ^19.2
  "@types/react-dom": ^19.2
  react: ^19.2
  react-dom: ^19.2
  tailwindcss: ^4.3.3
  "@tailwindcss/vite": ^4.3.3
  typescript: ~6
  typescript-eslint: ^8
  "@heroui/react": ^3.2.4
  "@heroui/styles": ^3.2.4
